version: '3.7'
services:
  api:
    build:
      context: .
      network: host
    image: "krossnine/sharp-server:${VERSION:-latest}"
    container_name: sharp-server-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_NAME=sharp-server
      - LOG_LEVEL=debug
    ports:
      - "3000:3000"